### PR TITLE
Add follower failure test

### PR DESCRIPTION
**Pull request by lukedirtwalker**
Tests that we can tolerate a failure of the follower node without problems.

---
This change is [Reviewable](https://reviewable.io/reviews/anapaya/patroni/7)

### CODE REVIEW

**Review by worxli — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/7)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @worxli)

**Review by worxli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/7)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @worxli)

___
*[acceptance/follower_failure_acceptance/test.py, line 38 at r1](https://reviewable.io/reviews/anapaya/patroni/7#-LaswKno6eu_0YASQ-be:-LaswKnp5rN98DPbdex7:bb7lgoe) ([raw file](https://github.com/anapaya/patroni/blob/5d068e7ceff40077c8d8a2165c114a07961b81f8/acceptance/follower_failure_acceptance/test.py#L38)):*
> ```Python
>         self.util.test_not_writable(replica)
> 
>         # No kill the replica
> ```

now?

**Review by worxli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/7)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @worxli)

___
*[acceptance/follower_failure_acceptance/test.py, line 33 at r1](https://reviewable.io/reviews/anapaya/patroni/7#-LaswsytDPiJJKYLziqt:-LaswsytDPiJJKYLziqu:b-wecu5p) ([raw file](https://github.com/anapaya/patroni/blob/5d068e7ceff40077c8d8a2165c114a07961b81f8/acceptance/follower_failure_acceptance/test.py#L33)):*
> ```Python
>             sys.exit(1)
> 
>         self.util.test_write_to(ln, 1)
> ```

if this fails, it doesn't exit?

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/7)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @worxli)

___
*[acceptance/follower_failure_acceptance/test.py, line 33 at r1](https://reviewable.io/reviews/anapaya/patroni/7#-LaswsytDPiJJKYLziqt:-LatkjBO3iYSGD1LLJX-:bcjjmv9) ([raw file](https://github.com/anapaya/patroni/blob/5d068e7ceff40077c8d8a2165c114a07961b81f8/acceptance/follower_failure_acceptance/test.py#L33)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

if this fails, it doesn't exit?
</blockquote></details>

It does it will throw an exception. Plumbum throws an exception if a command doesn't return with a 0 exit status.
___
*[acceptance/follower_failure_acceptance/test.py, line 38 at r1](https://reviewable.io/reviews/anapaya/patroni/7#-LaswKno6eu_0YASQ-be:-LatkioJ-EIQA_F2JpzL:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/5d068e7ceff40077c8d8a2165c114a07961b81f8/acceptance/follower_failure_acceptance/test.py#L38)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

now?
</blockquote></details>

Done.

**Review by worxli — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
