### PR TITLE
Add initial acceptance test

### PR DESCRIPTION
**Pull request by lukedirtwalker**
This change is [Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)

### CODE REVIEW

**Review by worxli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[.buildkite/scripts/acceptance, line 13 at r1](https://reviewable.io/reviews/anapaya/patroni/3#-LaUxSfy1quO9ROoo9Qx:-LaUxSfy1quO9ROoo9Qy:b-l6mwxj) ([raw file](https://github.com/anapaya/patroni/blob/99bf0f781519eee8cd0f4384bd7e3b7814149b0a/.buildkite/scripts/acceptance#L13)):*
> ```
> 
> # Run acceptance tests
> echo "do some tests now"
> ```

remove
___
*[.buildkite/scripts/acceptance, line 15 at r1](https://reviewable.io/reviews/anapaya/patroni/3#-LaUxix5ERVYTsG8a7lz:-LaUxix5ERVYTsG8a7m-:bg4uarj) ([raw file](https://github.com/anapaya/patroni/blob/99bf0f781519eee8cd0f4384bd7e3b7814149b0a/.buildkite/scripts/acceptance#L15)):*
> ```
> echo "do some tests now"
> export PYTHONPATH=acceptance/:.
> ARTIFACTS_DIR=/tmp/tst1/ ./acceptance/leader_failure_acceptance/test.py setup
> ```

`for i in ./acceptance/*_acceptance; do` something like this?

**Review by worxli — COMMENTED** [review]
> Reviewed 2 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 2 of 15 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 2 of 16 files reviewed, 2 unresolved discussions (waiting on @worxli)

___
*[.buildkite/scripts/acceptance, line 13 at r1](https://reviewable.io/reviews/anapaya/patroni/3#-LaUxSfy1quO9ROoo9Qx:-LaV7GcK4yWufQ-TzaKq:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/99bf0f781519eee8cd0f4384bd7e3b7814149b0a/.buildkite/scripts/acceptance#L13)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[.buildkite/scripts/acceptance, line 15 at r1](https://reviewable.io/reviews/anapaya/patroni/3#-LaUxix5ERVYTsG8a7lz:-LaV7HDt-DAqJU2DT8sp:bhk1r0c) ([raw file](https://github.com/anapaya/patroni/blob/99bf0f781519eee8cd0f4384bd7e3b7814149b0a/.buildkite/scripts/acceptance#L15)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

`for i in ./acceptance/*_acceptance; do` something like this?
</blockquote></details>

Added a function

**Review by worxli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 2 of 16 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[.buildkite/scripts/acceptance, line 19 at r2](https://reviewable.io/reviews/anapaya/patroni/3#-LaVIMDT2wKmFhQWvoYV:-LaVIMDT2wKmFhQWvoYW:b-ufmtdt) ([raw file](https://github.com/anapaya/patroni/blob/613e40edd27d78d89bf652e5db3d34da4667576b/.buildkite/scripts/acceptance#L19)):*
> ```
>     local TEST_NAME="$1"
>     echo "Running: $TEST_NAME"
>     local TST_DIR="$TOUT_DIR/$TEST_NAME"
> ```

what if the dir doesn't exist? maybe: 
```
TOUT_DIR=$(mktemp -d /tmp/tout.XXXXXX)
 ...
local TST_DIR="$TOUT_DIR/$TEST_NAME"
mkdir -p $TST_DIR
...
```

**Review by worxli — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 3 of 16 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 3 of 17 files reviewed, 4 unresolved discussions (waiting on @worxli)

___
*[.buildkite/scripts/acceptance, line 19 at r2](https://reviewable.io/reviews/anapaya/patroni/3#-LaVIMDT2wKmFhQWvoYV:-LaZQ-iN4IAq3pSUo_9Q:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/613e40edd27d78d89bf652e5db3d34da4667576b/.buildkite/scripts/acceptance#L19)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

what if the dir doesn't exist? maybe: 
```
TOUT_DIR=$(mktemp -d /tmp/tout.XXXXXX)
 ...
local TST_DIR="$TOUT_DIR/$TEST_NAME"
mkdir -p $TST_DIR
...
```
</blockquote></details>

Done.
___
*[acceptance/leader_failure_acceptance/test.py, line 3 at r3](https://reviewable.io/reviews/anapaya/patroni/3#-LaZRx0k4dlYQamcPw4V:-LaZRx0k4dlYQamcPw4W:b-rtagwg) ([raw file](https://github.com/anapaya/patroni/blob/82c77228bf308d12c679e3895460586923c0cc15/acceptance/leader_failure_acceptance/test.py#L3)):*
> ```Python
> #!/usr/bin/env python3
> 
> import json
> ```

delete
___
*[acceptance/leader_failure_acceptance/test.py, line 8 at r3](https://reviewable.io/reviews/anapaya/patroni/3#-LaZRyuiD5dhOc7Ypa9Y:-LaZRyuiD5dhOc7Ypa9Z:b-rtagwg) ([raw file](https://github.com/anapaya/patroni/blob/82c77228bf308d12c679e3895460586923c0cc15/acceptance/leader_failure_acceptance/test.py#L8)):*
> ```Python
> import time
> 
> from plumbum import cli
> ```

delete
___
*[acceptance/leader_failure_acceptance/test.py, line 9 at r3](https://reviewable.io/reviews/anapaya/patroni/3#-LaZRzgUEDXx3RxbHmQR:-LaZRzgUEDXx3RxbHmQS:b-rtagwg) ([raw file](https://github.com/anapaya/patroni/blob/82c77228bf308d12c679e3895460586923c0cc15/acceptance/leader_failure_acceptance/test.py#L9)):*
> ```Python
> 
> from plumbum import cli
> from plumbum.cmd import (
> ```

delete

**Review by worxli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 3 of 17 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[.buildkite/scripts/acceptance, line 15 at r4](https://reviewable.io/reviews/anapaya/patroni/3#-LaZUATw6X_p9MjHQaD5:-LaZUATw6X_p9MjHQaD6:b-kuhlf6) ([raw file](https://github.com/anapaya/patroni/blob/765733f4c964457012e232616bd3c82ee1c97bc4/.buildkite/scripts/acceptance#L15)):*
> ```
> 
> run_test() {
>     set -e
> ```

not needed, there is already one at the top of the file

**Review by worxli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 3 of 17 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[acceptance/2node_consul_leader_failure_acceptance/test.py, line 0 at r3](https://reviewable.io/reviews/anapaya/patroni/3#-LaZV16p6YA4d2pMyNL7:-LaZV16p6YA4d2pMyNL8:b-bnytd0) ([raw file](https://github.com/anapaya/patroni/blob/3dd0cd84b8a8f337d83fb7de949ce5165d8976dd/acceptance/2node_consul_leader_failure_acceptance/test.py#L0)):*
why is there an empty test?

**Review by oncilla — CHANGES_REQUESTED** [review]
> Reviewed 6 of 15 files at r1, 7 of 8 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker and @Oncilla)

___
*[acceptance/common/test.py, line 27 at r4](https://reviewable.io/reviews/anapaya/patroni/3#-La_8OGB1VJKCyVhNue9:-La_8OGB1VJKCyVhNueA:bggq2fc) ([raw file](https://github.com/anapaya/patroni/blob/765733f4c964457012e232616bd3c82ee1c97bc4/acceptance/common/test.py#L27)):*
> ```Python
>     tst_dir = local.path()  # Just init so mypy knows the type.
> 
>     @cli.switch("--artifacts-dir", str, envname="ARTIFACTS_DIR")
> ```

The artifacts dir is required for the test to work.
add `mandatory=True`
___
*[acceptance/leader_failure_acceptance/test.py, line 14 at r4](https://reviewable.io/reviews/anapaya/patroni/3#-La_Ccu7C40xE9tNwk3E:-La_Ccu7C40xE9tNwk3F:broorsu) ([raw file](https://github.com/anapaya/patroni/blob/765733f4c964457012e232616bd3c82ee1c97bc4/acceptance/leader_failure_acceptance/test.py#L14)):*
> ```Python
> 
> 
> class Test(test.Base):
> ```

The following should also work:
````
@test.Base.subcommand("run")
class TestRun(test.Base):
    ...

if __name__ == "__main__":
    initLog()
    test.Base()
````

What do you prefer? I have no strong opinion on this.

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 14 of 16 files reviewed, 4 unresolved discussions (waiting on @Oncilla and @worxli)

___
*[.buildkite/scripts/acceptance, line 15 at r4](https://reviewable.io/reviews/anapaya/patroni/3#-LaZUATw6X_p9MjHQaD5:-La_IisXESmk1x_wzVWu:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/765733f4c964457012e232616bd3c82ee1c97bc4/.buildkite/scripts/acceptance#L15)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

not needed, there is already one at the top of the file
</blockquote></details>

Done.
___
*[acceptance/2node_consul_leader_failure_acceptance/test.py, line  at r3](https://reviewable.io/reviews/anapaya/patroni/3#-LaZV16p6YA4d2pMyNL7:-La_Ipwn6FUzM-mtQTZm:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/3dd0cd84b8a8f337d83fb7de949ce5165d8976dd/acceptance/2node_consul_leader_failure_acceptance/test.py#L)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

why is there an empty test?
</blockquote></details>

Done.
___
*[acceptance/common/test.py, line 27 at r4](https://reviewable.io/reviews/anapaya/patroni/3#-La_8OGB1VJKCyVhNue9:-La_IxwtE78OLCMzFPSb:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/765733f4c964457012e232616bd3c82ee1c97bc4/acceptance/common/test.py#L27)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

The artifacts dir is required for the test to work.
add `mandatory=True`
</blockquote></details>

Done.
___
*[acceptance/leader_failure_acceptance/test.py, line 14 at r4](https://reviewable.io/reviews/anapaya/patroni/3#-La_Ccu7C40xE9tNwk3E:-La_JDQl4MzFn20VUz7S:bdne8zi) ([raw file](https://github.com/anapaya/patroni/blob/765733f4c964457012e232616bd3c82ee1c97bc4/acceptance/leader_failure_acceptance/test.py#L14)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

The following should also work:
````
@test.Base.subcommand("run")
class TestRun(test.Base):
    ...

if __name__ == "__main__":
    initLog()
    test.Base()
````

What do you prefer? I have no strong opinion on this.
</blockquote></details>

This class will display the comment if you run the binary without arguments. So I'd leave it.

**Review by worxli — COMMENTED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @Oncilla)

**Review by oncilla — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/3#-:-La_P-bxBlHu9Nz50zOw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
