### PR TITLE
Force leadership after consul is back up

### PR DESCRIPTION
**Pull request by lukedirtwalker**
In the node that was leader attempt to acquire leader until we have it.
Also write back values that we stored during static_mode

---
This change is [Reviewable](https://reviewable.io/reviews/anapaya/patroni/10)

### CODE REVIEW

**Review by oncilla — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/10)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[patroni/ha.py, line 1202 at r1](https://reviewable.io/reviews/anapaya/patroni/10#-Lb3MDzJ3fD38PtLefdM:-Lb3MDzKCZ_9uB7sAXG2:bhv36qm) ([raw file](https://github.com/anapaya/patroni/blob/d05c5f9dacc68c92e54877858456a5c66eaac8e2/patroni/ha.py#L1202)):*
> ```Python
>                 # sleep a bit to make sure the other node can acquire leadership.
>                 time.sleep(1)
>                 return 'release leader key volunatrily after dcs is back working'
> ```

`voluntarily`
___
*[patroni/dcs/consul2node.py, line 82 at r1](https://reviewable.io/reviews/anapaya/patroni/10#-Lb3MJjWCLzwoU3kMimv:-Lb3MJjWCLzwoU3kMimw:b21lt3k) ([raw file](https://github.com/anapaya/patroni/blob/d05c5f9dacc68c92e54877858456a5c66eaac8e2/patroni/dcs/consul2node.py#L82)):*
> ```Python
>                     leader = self.attempt_to_acquire_leader()
>                     while not leader:
>                         leader = self.attempt_to_acquire_leader()
> ```

Should we have a maximum number of retries maybe?

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/10)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Oncilla)

___
*[patroni/ha.py, line 1202 at r1](https://reviewable.io/reviews/anapaya/patroni/10#-Lb3MDzJ3fD38PtLefdM:-Lb3Sn43C_o3En1b9CFU:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d05c5f9dacc68c92e54877858456a5c66eaac8e2/patroni/ha.py#L1202)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

`voluntarily`
</blockquote></details>

Done.
___
*[patroni/dcs/consul2node.py, line 82 at r1](https://reviewable.io/reviews/anapaya/patroni/10#-Lb3MJjWCLzwoU3kMimv:-Lb3UBqB2cB8eqkzZj8h:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d05c5f9dacc68c92e54877858456a5c66eaac8e2/patroni/dcs/consul2node.py#L82)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Should we have a maximum number of retries maybe?
</blockquote></details>

Done.

**Review by oncilla — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/10#-:-Lb3UbvS3xviOCeOacnT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by oncilla — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/10#-:-Lb3_KId5YzswjP3eW13:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
