### PR TITLE
Enable patroni acceptance tests

### PR DESCRIPTION
**Pull request by worxli**
This change is [Reviewable](https://reviewable.io/reviews/anapaya/patroni/2)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/2)* status: all files reviewed, 2 unresolved discussions (waiting on @worxli)

___
*[.buildkite/files/Dockerfile, line 1 at r1](https://reviewable.io/reviews/anapaya/patroni/2#-LaU6elMDQnaedkCAoeb:-LaU6elN8KmiSKzpIUTS:b4j151t) ([raw file](https://github.com/anapaya/patroni/blob/514cfdbc103100cb18f4d83c5f3ab4cae1b6eb94/.buildkite/files/Dockerfile#L1)):*
> ```Dockerfile
> FROM python:3.5
> ```

Interesting choice to have python as base.
Wouldn't it be better to use the `3.5-slim` version? (see https://hub.docker.com/_/python/)
___
*[.buildkite/files/Dockerfile, line 18 at r1](https://reviewable.io/reviews/anapaya/patroni/2#-LaU4IJV7AIUcO_qB1B5:-LaU4IJX3HcOT_wIv5ZM:b-sdvq4s) ([raw file](https://github.com/anapaya/patroni/blob/514cfdbc103100cb18f4d83c5f3ab4cae1b6eb94/.buildkite/files/Dockerfile#L18)):*
> ```Dockerfile
> 
> RUN pip3 install --user -r requirements.txt
> RUN curl -L https://releases.hashicorp.com/consul/${CONSULVERSION}/consul_${CONSULVERSION}_linux_amd64.zip \
> ```

Why do we need consul in this container? I don't think that's needed.

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/2)* status: all files reviewed, 1 unresolved discussion (waiting on @worxli)

___
*[.buildkite/files/Dockerfile, line 18 at r1](https://reviewable.io/reviews/anapaya/patroni/2#-LaU4IJV7AIUcO_qB1B5:-LaUCma53UPg4Isyt31G:b-td104i) ([raw file](https://github.com/anapaya/patroni/blob/514cfdbc103100cb18f4d83c5f3ab4cae1b6eb94/.buildkite/files/Dockerfile#L18)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Why do we need consul in this container? I don't think that's needed.
</blockquote></details>

Needed for the patroni tests.

**Review by worxli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/2)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[.buildkite/files/Dockerfile, line 1 at r1](https://reviewable.io/reviews/anapaya/patroni/2#-LaU6elMDQnaedkCAoeb:-LaUGZXlE4dXKzHpK_sk:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/514cfdbc103100cb18f4d83c5f3ab4cae1b6eb94/.buildkite/files/Dockerfile#L1)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Interesting choice to have python as base.
Wouldn't it be better to use the `3.5-slim` version? (see https://hub.docker.com/_/python/)
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/2#-:-LaUIcG77jILWpx6vIQx:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
