### PR TITLE
Add buildkite CI

### PR DESCRIPTION
**Pull request by worxli**
This change is [Reviewable](https://reviewable.io/reviews/anapaya/patroni/1)

### CODE REVIEW

**Review by lukedirtwalker — APPROVED** [review]
:shipit: :lgtm: 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/1#-:-LaQ0cbJE_eU8Vkld4ad:b-291ou)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/1)* status: all files reviewed, 1 unresolved discussion (waiting on @worxli)

___
*[.buildkite/scripts/unit, line 20 at r1](https://reviewable.io/reviews/anapaya/patroni/1#-LaQ16F0076ckYE9TKPV:-LaQ16F0076ckYE9TKPW:b-fsj8v1) ([raw file](https://github.com/anapaya/patroni/blob/68b5b2e1c3deab1e7855a3c521416c7950104bd2/.buildkite/scripts/unit#L20)):*
> ```
> pip3 install -r requirements.txt
> pip3 install behave codacy-coverage coverage coveralls flake8 mock pytest-cov pytest setuptools
> ```

Could we make everything before the test silent?

**Review by worxli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/1)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[.buildkite/scripts/unit, line 20 at r1](https://reviewable.io/reviews/anapaya/patroni/1#-LaQ16F0076ckYE9TKPV:-LaQ4B4N-PQKxaXlJN8j:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/68b5b2e1c3deab1e7855a3c521416c7950104bd2/.buildkite/scripts/unit#L20)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Could we make everything before the test silent?
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
