### PR TITLE
Add 2 node consul failure tolerance

### PR DESCRIPTION
**Pull request by lukedirtwalker**
Add a consul2node dcs that can deal with failures of one consul node.
The node that can't reach consul will drop leadership.
The node that can reach consul and sees "500 no cluster leader" becomes leader.
This assumes that split brain can not happen.

---
This change is [Reviewable](https://reviewable.io/reviews/anapaya/patroni/5)

### CODE REVIEW

**Comment by lukedirtwalker** [comment]
will reopen against anapaya branch.

**Comment by lukedirtwalker** [comment]
will reopen against anapaya branch.

**Review by oncilla — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/5)* status: 5 of 8 files reviewed, 16 unresolved discussions (waiting on @lukedirtwalker and @Oncilla)

___
*[patroni/ha.py, line 78 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau2KL1CPrPwO0-yNXd:-Lau2KL1CPrPwO0-yNXe:byv1ugw) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/ha.py#L78)):*
> ```Python
>         # TODO(lukedirtwalker): consider: instead of this, handle this in consul by setting _session
>         # = "y" when losing cluster connection.
>         self.dcs_failed = False
> ```

this should probably be private (i.e. suffix `_`)
___
*[patroni/ha.py, line 1214 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau2Qoh4kw-9lps7C0I:-Lau2Qoh4kw-9lps7C0J:b-gz6717) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/ha.py#L1214)):*
> ```Python
>                 self.cluster = self.dcs.get_cluster()
> 
>             if dcs_failed_before and self.has_lock():
> ```

Why doe we need to release the leader key?
___
*[patroni/dcs/consul.py, line 66 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau4AEW36Xk3tbOdcRS:-Lau4AEW36Xk3tbOdcRT:b5kldm0) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul.py#L66)):*
> ```
> https://www.consul.io/docs/agent/options.html#rpc_hold_timeout
> ```

What if consul is configured with a different `rpc_hold_timeout`?
___
*[patroni/dcs/consul.py, line 153 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau5W1c9Dfit2jqms1J:-Lau5W1c9Dfit2jqms1K:b-92uv6u) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul.py#L153)):*
> ```Python
>         try:
>             return func(*args, **kwargs)
>         except ConsulNoClusterLeader as err:
> ```

Simplify
````
except ConsulNoClusterLeader:
  raise
````

If I understand this correctly, running consul without 2node setup will break?
___
*[patroni/dcs/consul.py, line 365 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau72iW41KG888siL1r:-Lau72iW41KG888siL1s:b-7ropln) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul.py#L365)):*
> ```Python
>             return Cluster(None, None, None, None, [], None, None, None)
>         except ConsulNoClusterLeader as err:
>             raise err
> ```

ditto
___
*[patroni/dcs/consul.py, line 393 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau7TjxDYwEpQVrl4VY:-Lau7TjxDYwEpQVrl4VZ:b-7ropln) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul.py#L393)):*
> ```Python
>             logger.error('Our session disappeared from Consul, can not "touch_member"')
>         except ConsulNoClusterLeader as err:
>             raise err
> ```

ditto
___
*[patroni/dcs/consul2node.py, line 29 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau86rq7brlkrOQ40uD:-Lau86rq7brlkrOQ40uE:bnanxsy) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L29)):*
> ```Python
> 
> def try_super(func):
>     '''
> ```

Use `"""` instead
___
*[patroni/dcs/consul2node.py, line 43 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau8r0M9YppRUwFedIE:-Lau8r0M9YppRUwFedIF:bwy4yhs) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L43)):*
> ```Python
>             args = tuple(largs[1:])
>             if func.__name__ == 'touch_member':
>                 logger.warn("Calling touch_member super")
> ```

`warn` is deprecated. Use `warning` instead.
Why is this here? Left over debug or some specific reason?
___
*[patroni/dcs/consul2node.py, line 46 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauB1Pt7DEt6a2Srndb:-LauB1Pt7DEt6a2Srndc:bjoe9fc) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L46)):*
> ```Python
>             return getattr(_super, func.__name__)(*args, **kwargs)
>         except consul.ConsulNoClusterLeader:
>             logger.warning("%s: %s", func.__name__, NO_CONSUL_LEADER)
> ```

Should this return `False`?
___
*[patroni/dcs/consul2node.py, line 56 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauIJf7733TsDstz0ZL:-LauIJf7733TsDstz0ZM:b-2kbiik) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L56)):*
> ```Python
>     accessible). If the local consul is still available but responds with "500 no cluster leader"
>     assume we are the only running node, thus we get to be leader.
>     NOTE: This obviously only works if you can never have a split brain. Otherwise have fun ;).
> ```

Maybe mention that the consul agents that Patroni connects to must be the consul servers themselves, otherwise all agents are reachable and receive the 500 error. 
___
*[patroni/dcs/consul2node.py, line 62 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauC3pNE0vyzsU4_ZKW:-LauC3pNE0vyzsU4_ZKX:b-jofqix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L62)):*
> ```Python
>         self._static_mode = False
>         self._static_cluster = None
>         self._static_retries = 0
> ```

this does not seem to be used anywhere
___
*[patroni/dcs/consul2node.py, line 66 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauBA089o9kaR16raTo:-LauBA089o9kaR16raTp:b-8tifqr) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L66)):*
> ```Python
>         # set_read_timeout divides by 3, we need at least 8 seconds.
>         # Consul waits up to 7 seconds, see https://www.consul.io/docs/agent/options.html#rpc_hold_timeout
>         self._client.http.set_read_timeout(3 * 8)
> ```

You have set this to 8 already in set_read_timeout
___
*[patroni/dcs/consul2node.py, line 77 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauHstD-JkALpibNIAL:-LauHstD-JkALpibNIAM:b4ne2cq) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L77)):*
> ```Python
>         # load cluster is called periodically so we always try to get from consul.
>         try:
>             cluster = super()._load_cluster()
> ```

In case the consul agent is not reachable, is this cluster `None` and no exception is thrown?
___
*[patroni/dcs/consul2node.py, line 90 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauCKNX0Z_J5KXSPZJ8:-LauCKNX0Z_J5KXSPZJ9:ba87dve) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L90)):*
> ```Python
>             # Enable static mode.
>             c = self._static_cluster
>             # TODO maybe keep leader if we already were leader?
> ```

add your name.
___
*[patroni/dcs/consul2node.py, line 127 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauH9zk-qcp1mIu4Hbx:-LauH9zk-qcp1mIu4Hby:bq7t733) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L127)):*
> ```Python
>                 c = self._static_cluster
>                 member = Member(-1, self._name, None, {})
>                 member = ([m for m in c.members if m.name == self._name] or [member])[0]
> ```

what about `member = next((m for m in c.members if m.name == self._name), Member(-1, self._name, None, {}))` ?
___
*[patroni/dcs/consul2node.py, line 143 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauJ3Za3zqbq7jVmX7-:-LauJ3Za3zqbq7jVmX70:bmoxch2) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L143)):*
> ```Python
>         if self._static_mode:
>             c = self._static_cluster
>             self._static_cluster = Cluster(c.initialize, c.config, c.leader, last_operation,
> ```

Does it matter that this information is not written in the kv store?
(same for other places)

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/5)* status: 1 of 9 files reviewed, 16 unresolved discussions (waiting on @Oncilla)

___
*[patroni/ha.py, line 78 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau2KL1CPrPwO0-yNXd:-LauMd_c1s4Sw6za0O3C:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/ha.py#L78)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

this should probably be private (i.e. suffix `_`)
</blockquote></details>

Done.
___
*[patroni/ha.py, line 1214 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau2Qoh4kw-9lps7C0I:-LauMdxa5Nc7vpqsxvoz:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/ha.py#L1214)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Why doe we need to release the leader key?
</blockquote></details>

Done.
___
*[patroni/dcs/consul.py, line 66 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau4AEW36Xk3tbOdcRS:-Lazeosb0d_eCYeG0SHI:b-64zv2m) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul.py#L66)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

> ```
> https://www.consul.io/docs/agent/options.html#rpc_hold_timeout
> ```

What if consul is configured with a different `rpc_hold_timeout`?

</blockquote></details>

Done. Added consul_timeout configuration for this.
___
*[patroni/dcs/consul.py, line 153 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau5W1c9Dfit2jqms1J:-LazesyeD4Y0wNpkG6l1:b-x9a18g) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul.py#L153)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Simplify
````
except ConsulNoClusterLeader:
  raise
````

If I understand this correctly, running consul without 2node setup will break?

</blockquote></details>

Also made this a config, so the behavior can be disabled.
___
*[patroni/dcs/consul.py, line 365 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau72iW41KG888siL1r:-Lazf9AIDZTMRyHjqZZK:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul.py#L365)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[patroni/dcs/consul.py, line 393 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau7TjxDYwEpQVrl4VY:-Lazf9TX6J-NZhL7zCIz:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul.py#L393)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[patroni/dcs/consul2node.py, line 29 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau86rq7brlkrOQ40uD:-LauN4lT6p5apgKtrCMt:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L29)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Use `"""` instead
</blockquote></details>

Done.
___
*[patroni/dcs/consul2node.py, line 43 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-Lau8r0M9YppRUwFedIE:-LauNAUk5E5JlPivikns:b-ryzjee) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L43)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

`warn` is deprecated. Use `warning` instead.
Why is this here? Left over debug or some specific reason?
</blockquote></details>

Left over, removed.
___
*[patroni/dcs/consul2node.py, line 46 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauB1Pt7DEt6a2Srndb:-LauNX-pBuaT82tmkiFd:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L46)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Should this return `False`?
</blockquote></details>

Done.
___
*[patroni/dcs/consul2node.py, line 56 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauIJf7733TsDstz0ZL:-LauRjL440EAX5TinE3l:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L56)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Maybe mention that the consul agents that Patroni connects to must be the consul servers themselves, otherwise all agents are reachable and receive the 500 error. 
</blockquote></details>

Done.
___
*[patroni/dcs/consul2node.py, line 62 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauC3pNE0vyzsU4_ZKW:-LauN_7JE0kT9uUAhy20:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L62)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

this does not seem to be used anywhere
</blockquote></details>

Done.
___
*[patroni/dcs/consul2node.py, line 66 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauBA089o9kaR16raTo:-LauNcDz1w_K5AbqA14n:b-3s2six) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L66)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

You have set this to 8 already in set_read_timeout
</blockquote></details>

yes, that's a left over.
___
*[patroni/dcs/consul2node.py, line 77 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauHstD-JkALpibNIAL:-LauNhRLCe86sem-wOa4:bxi382l) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L77)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

In case the consul agent is not reachable, is this cluster `None` and no exception is thrown?
</blockquote></details>

Nope it will throw another exception of type `ConsulError`
___
*[patroni/dcs/consul2node.py, line 90 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauCKNX0Z_J5KXSPZJ8:-LauOR3F7uxM3nKxnzph:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L90)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

add your name.
</blockquote></details>

Done.
___
*[patroni/dcs/consul2node.py, line 127 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauH9zk-qcp1mIu4Hbx:-LauPQAN0nUgHGwh7Y1C:b-896fix) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L127)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

what about `member = next((m for m in c.members if m.name == self._name), Member(-1, self._name, None, {}))` ?
</blockquote></details>

Done.
___
*[patroni/dcs/consul2node.py, line 143 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauJ3Za3zqbq7jVmX7-:-LauOU3-EjUh9VVjrRdN:b-d0qzbx) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L143)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Does it matter that this information is not written in the kv store?
(same for other places)
</blockquote></details>

Partially. It would be problematic if this node also fails during this mode. But that is the best we can do. 1 full node failure, if more fails, this will no longer work.

**Review by oncilla — APPROVED** [review]
:lgtm:

> Reviewed 7 of 8 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/5#-:-LazzOIkCsCeEcnf_h0K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[patroni/dcs/consul2node.py, line 77 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauHstD-JkALpibNIAL:-Lazy7cU2XjtL1j9Q_Ru:b-16tcmz) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L77)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Nope it will throw another exception of type `ConsulError`
</blockquote></details>

Exceptions, so discoverable :)

**Review by oncilla — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/5#-:-Lb-1ksv8o8jsYjuNe11:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/patroni/5)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[patroni/dcs/consul2node.py, line 77 at r1](https://reviewable.io/reviews/anapaya/patroni/5#-LauHstD-JkALpibNIAL:-Lb26w4T8boreFyWjE-A:bmb0sol) ([raw file](https://github.com/anapaya/patroni/blob/d848d51a5011b726b0deb1c0d1cd41fe9bfc87e4/patroni/dcs/consul2node.py#L77)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Exceptions, so discoverable :)
</blockquote></details>

Haha, yeah agreed :)

**Pull request merged**
